services:
  jekyll:
    image: wildaboutpilates:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./bin/dev:/usr/local/sbin
      - ./jekyll:/jekyll
    # stdin_open: true
    # tty: true
